apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-conf
data:
  host: "mysql-service"
  dbname: "testdb"
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  selector:
    app: backend
  ports:
    - port: 8080
      targetPort: 8080
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend-container
          image: mehdiboutoumit/tutorials-app:spring-backend
          ports:
            - containerPort: 8080
              name: backend-port
          env:
            - name: DB_HOST
              valueFrom:
                configMapKeyRef:
                  name: mysql-conf
                  key: host
            - name: DB_PORT
              value: "3306"
            - name: DB_NAME
              valueFrom:
                configMapKeyRef:
                  name: mysql-conf
                  key: dbname
            - name: DB_USERNAME
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: mysql-secret
                  key: MYSQL_ROOT_PASSWORD
          readinessProbe:
            exec:
              command:
              - cat
              - /tmp/healthy
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            exec:
              command:
              - cat
              - /tmp/healthy
            initialDelaySeconds: 10
            periodSeconds: 15
          startupProbe:
            exec:
              command:
              - cat
              - /tmp/healthy
            failureThreshold: 30    



